# This is a basic workflow to help you get started with Actions

name: Build Blog Post

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Call Search.list API to get the videoID
      - name: Http Search Request 
        id: SearchRequest
        uses: fjogeleit/http-request-action@master
        with: 
          url: 'https://www.googleapis.com/youtube/v3/search?key=${{ secrets.GOOGLEAPIKEY }}&part=id&channelId=UC2iybVI2TE2LQ6straknrnA&order=date'
          method: 'GET'
          
      - name: Show Response
        run: echo "${{ fromJson(steps.SearchRequest.outputs.response).items[0].id.videoId }}"
      
      # Call Video.list API to get details of video
      - name: Http Video Request 
        id: VideoRequest
        uses: fjogeleit/http-request-action@master
        with: 
          url: 'https://www.googleapis.com/youtube/v3/videos?key=${{ secrets.GOOGLEAPIKEY }}&part=snippet,contentDetails,statistics&id=${{ fromJson(steps.SearchRequest.outputs.response).items[0].id.videoId }}'
          method: 'GET'
        
      - name: Show Video Response
        run: echo "${{ fromJson(steps.VideoRequest.outputs.response).items[0].snippet.title }}"
          
      # populate the blog post
      - name: replace the tokens and copy the file
        uses: BlobDevelopment/copy-and-replace-token@v1
        with:
          source: './docs/_drafts/blogTemplate.markdown'
          target: './docs/_posts/2021-11-10-Automated-Content-Creation.markdown'
        env:
          title: "${{ fromJson(steps.VideoRequest.outputs.response).items[0].snippet.title }}"
          description: "${{ fromJson(steps.VideoRequest.outputs.response).items[0].snippet.description }}"
          id: "${{ fromJson(steps.VideoRequest.outputs.response).items[0].id }}"
        
      - name: checkin updates
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated new blog post"
          git push
     
      # push to gh-pages repo
      
